# Generated by Django 4.0.1 on 2022-01-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammember', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='phone',
            field=models.CharField(default=4567890, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
