# Generated by Django 4.0.1 on 2022-01-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammember', '0002_people_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
