# Generated by Django 4.0.1 on 2022-01-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammember', '0004_alter_people_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='choice',
            field=models.CharField(choices=[('memeber', "Regular - Can't delete members"), ('admin', 'Admin - Can delete members')], default='member', max_length=20),
        ),
    ]
