# Generated by Django 4.0.1 on 2022-01-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammember', '0005_alter_people_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='choice',
            field=models.CharField(choices=[('member', "Regular - Can't delete members"), ('admin', 'Admin - Can delete members')], default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='people',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='phone',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
