# Generated by Django 4.0.1 on 2022-01-16 22:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammember', '0006_alter_people_choice_alter_people_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='phone',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
